name: 📧 ChatGPT Enterprise Briefing

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send_briefing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Send ChatGPT Enterprise Briefing
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_SENDER_EMAIL: ${{ secrets.GMAIL_SENDER_EMAIL }}
        run: |
          cd $GITHUB_WORKSPACE
          python scripts/send_briefing.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: briefing-logs
          path: briefing_execution.log
