name: 📧 ChatGPT Enterprise Briefing

on:
  schedule:
    # Todos os dias às 20:00 BRT (0:00 UTC do dia seguinte)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite disparo manual

jobs:
  send_briefing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil
      
      - name: Send ChatGPT Enterprise Briefing
        env:
          RUBE_API_KEY: ${{ secrets.RUBE_API_KEY }}
          RUBE_SESSION_ID: ${{ secrets.RUBE_SESSION_ID }}
        run: python scripts/send_briefing.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: briefing-logs
          path: briefing_execution.log
